# Generated by Django 5.0.2 on 2025-03-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_application_method_product_base_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_type',
            field=models.CharField(blank=True, choices=[('water_acrylic', 'Водно-акриловая'), ('water_latex', 'Водно-латексная'), ('water_pva', 'Водно-дисперсионная ПВА'), ('water_silicone', 'Водно-силиконовая'), ('oil', 'Масляная'), ('alkyd', 'Алкидная'), ('polyurethane', 'Полиуретановая'), ('epoxy', 'Эпоксидная')], max_length=100, verbose_name='Тип основы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='surface_type',
            field=models.CharField(blank=True, choices=[('concrete', 'Бетон'), ('plaster', 'Штукатурка'), ('drywall', 'Гипсокартон'), ('wood', 'Дерево'), ('metal', 'Металл'), ('plastic', 'Пластик'), ('wallpaper', 'Обои'), ('brick', 'Кирпич'), ('facade', 'Фасад'), ('tile', 'Плитка')], max_length=200, verbose_name='Тип поверхности'),
        ),
    ]
