# Generated by Django 5.0.2 on 2025-03-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_base_type_alter_product_surface_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurfaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Тип поверхности',
                'verbose_name_plural': 'Типы поверхностей',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='surface_type',
        ),
        migrations.AddField(
            model_name='product',
            name='surface_types',
            field=models.ManyToManyField(to='shop.surfacetype', verbose_name='Типы поверхностей'),
        ),
    ]
