# Generated by Django 5.0.2 on 2025-03-22 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_sale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='technical_specifications',
        ),
        migrations.RemoveField(
            model_name='product',
            name='usage_instructions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='safety_instructions',
        ),
    ]
