# Generated by Django 5.0.2 on 2025-03-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20250322_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Код цвета'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='Новинка'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(default=False, verbose_name='Распродажа'),
        ),
        migrations.AddField(
            model_name='product',
            name='safety_instructions',
            field=models.TextField(blank=True, verbose_name='Инструкция по безопасности'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена по акции'),
        ),
        migrations.AddField(
            model_name='product',
            name='technical_specifications',
            field=models.TextField(blank=True, verbose_name='Технические характеристики'),
        ),
        migrations.AddField(
            model_name='product',
            name='usage_instructions',
            field=models.TextField(blank=True, verbose_name='Инструкция по применению'),
        ),
    ]
