# Generated by Django 5.0.2 on 2025-03-22 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_color_code_product_is_new_product_is_sale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_sale',
        ),
    ]
