# Generated by Django 5.0.2 on 2025-03-22 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_product_color_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='safety_instructions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='technical_specifications',
        ),
        migrations.RemoveField(
            model_name='product',
            name='usage_instructions',
        ),
    ]
