# Generated by Django 5.0.2 on 2025-03-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_product_safety_instructions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Месяц')),
                ('profit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Прибыль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Месячная прибыль',
                'verbose_name_plural': 'Месячная прибыль',
                'ordering': ['-month'],
                'unique_together': {('month',)},
            },
        ),
    ]
