# Generated by Django 5.1.7 on 2025-03-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_monthlyprofit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyprofit',
            options={'ordering': ['-month'], 'verbose_name': 'Прибыль за месяц', 'verbose_name_plural': 'Прибыль по месяцам'},
        ),
        migrations.AlterUniqueTogether(
            name='monthlyprofit',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='monthlyprofit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='monthlyprofit',
            name='month',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='monthlyprofit',
            name='profit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='monthlyprofit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
