# Generated by Django 5.1.7 on 2025-03-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_monthlyprofit_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='surface_types',
        ),
        migrations.RemoveField(
            model_name='product',
            name='application_method',
        ),
        migrations.RemoveField(
            model_name='product',
            name='base_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='coverage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='drying_time',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gloss_level',
        ),
        migrations.RemoveField(
            model_name='product',
            name='volume',
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100, verbose_name='Габариты (ШxВxГ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='ethernet_port',
            field=models.BooleanField(default=False, verbose_name='Наличие Ethernet порта'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_3d',
            field=models.BooleanField(default=False, verbose_name='Поддержка 3D'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_bluetooth',
            field=models.BooleanField(default=False, verbose_name='Наличие Bluetooth'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_dolby_atmos',
            field=models.BooleanField(default=False, verbose_name='Поддержка Dolby Atmos'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_dolby_vision',
            field=models.BooleanField(default=False, verbose_name='Поддержка Dolby Vision'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_hdr',
            field=models.BooleanField(default=False, verbose_name='Поддержка HDR'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_smart_tv',
            field=models.BooleanField(default=False, verbose_name='Поддержка Smart TV'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_wifi',
            field=models.BooleanField(default=False, verbose_name='Наличие Wi-Fi'),
        ),
        migrations.AddField(
            model_name='product',
            name='hdmi_ports',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество HDMI портов'),
        ),
        migrations.AddField(
            model_name='product',
            name='headphone_jack',
            field=models.BooleanField(default=False, verbose_name='Наличие разъема для наушников'),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='product',
            name='optical_audio',
            field=models.BooleanField(default=False, verbose_name='Наличие оптического аудио выхода'),
        ),
        migrations.AddField(
            model_name='product',
            name='power_consumption',
            field=models.CharField(blank=True, max_length=50, verbose_name='Потребляемая мощность'),
        ),
        migrations.AddField(
            model_name='product',
            name='resolution',
            field=models.CharField(blank=True, max_length=100, verbose_name='Разрешение'),
        ),
        migrations.AddField(
            model_name='product',
            name='screen_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Размер экрана (дюймы)'),
        ),
        migrations.AddField(
            model_name='product',
            name='usb_ports',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество USB портов'),
        ),
        migrations.DeleteModel(
            name='SurfaceType',
        ),
    ]
