# Generated by Django 5.1.7 on 2025-03-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_product_surface_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_features_description',
            field=models.TextField(blank=True, verbose_name='Описание дополнительных функций'),
        ),
        migrations.AddField(
            model_name='product',
            name='interfaces_description',
            field=models.TextField(blank=True, verbose_name='Описание интерфейсов'),
        ),
    ]
