# Generated by Django 5.1.7 on 2025-03-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_product_additional_features_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_additional_features',
            field=models.BooleanField(default=True, verbose_name='Показывать дополнительные функции'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_interfaces',
            field=models.BooleanField(default=True, verbose_name='Показывать интерфейсы'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_technical_specs',
            field=models.BooleanField(default=True, verbose_name='Показывать технические характеристики'),
        ),
        migrations.AddField(
            model_name='product',
            name='technical_specs_description',
            field=models.TextField(blank=True, verbose_name='Описание технических характеристик'),
        ),
    ]
